

[profile.default]
solc-version = "0.8.17"
optimizer = true
optimizer-runs = 200
src = "contracts"
out = "out"
libs = ["lib"]
gas_reports = ["*"]


[fuzz]
runs = 60000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config